### PR TITLE
Update gmx_mmpbsa version

### PR DESCRIPTION
**Pull request by npavlovikj**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by npavlovikj** [comment]
@marioernestovaldes , @Valdes-Tresanco-MS , can you please review this PR and let me know if any further updates are needed in order to have the conda-forge package updated?

**Review by Valdes-Tresanco-MS — APPROVED** [review]
It looks good for me. Thank you

**Comment by npavlovikj** [comment]
I am sorry for bothering you, but can this please be merged if there are no objections? I would like to install the newest version on our HPC Cluster since we have researchers requesting the software.

**Comment by npavlovikj** [comment]
Thank you 😄

**Pull request merged**
